sudo: true
language: c

os: osx
osx_image:
  - xcode8
  - xcode9.2
  - xcode10.1
compiler: clang

addons:
  homebrew:
    update: true
    packages:
      - python@3

install:
  - export PATH=$(brew --prefix llvm)/bin:$PATH

script:
  - export CODEBUILD_SRC_DIR=$(pwd)
  - python3 -c "from urllib.request import urlretrieve; urlretrieve('https://raw.githubusercontent.com/awslabs/aws-c-common/master/codebuild/builder.py', 'builder.py')"
  - python3 builder.py build macos-default-default-macos-x64
