sudo: true
language: c

os: osx
osx_image:
  - xcode8
  - xcode9.2
  - xcode10.1
compiler: clang

addons:
  homebrew:
    update: true
    packages:
      - python@3

script:
  - ./codebuild/common-posix.sh -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
