name: ClangASanUBSan

on: [push]

jobs:
  clang-tsan:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt-get install ninja-build
      
    - name: Build and test
      run: |
        ./build-deps.sh -DCMAKE_C_COMPILER=clang -DENABLE_SANITIZERS=ON -DSANITIZERS=",address,undefined"
        cd build
        cmake -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_SANITIZERS=ON -DSANITIZERS=",address,undefined" -DCMAKE_PREFIX_PATH=`pwd`/deps/install/ ..
        ninja
        cd tests
        ctest --verbose
