name: ClangTSan

on: [push]

jobs:
  clang-tsan:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt-get install ninja-build
      
    - name: Build and test
      run: |
        ./build-deps.sh -DCMAKE_C_COMPILER=clang -DENABLE_SANITIZERS=ON -DSANITIZERS=",thread"
        cd build
        cmake -GNinja -DCMAKE_C_COMPILER=clang -DENABLE_SANITIZERS=ON -DSANITIZERS=",thread" -DCMAKE_PREFIX_PATH=`pwd`/deps/install/ ..
        ninja
        cd tests
        TSAN_OPTIONS="suppressions=`pwd`/../../.tsan_suppressions.txt" ctest --verbose
